[package]
name = "agent"
version = "0.1.0"
edition = "2021"
authors = [
  "Oenga John <johnongwae4@gmail.com"
]
description = "<to be filled>"



[workspace]
members = [
#   "agent-cli",
#   "system",
#   "exporters",
#   "config",
#   "utils",
#   "net"
]